import 'package:flutter/material.dart';
import '../theme/app_spacing.dart';

/// A small, tasteful indicator shown next to calculated Panchangam /
/// Jatakam values so it is always clear this is preview/development
/// data rather than a verified calculation. Deliberately subtle —
/// informational, not alarming.
class MockDataBadge extends StatelessWidget {
  const MockDataBadge({super.key, this.label = 'Preview calculation'});

  final String label;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Tooltip(
      message: 'This value is generated by a development placeholder, not a verified Panchangam/Jyotisha engine.',
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: AppSpacing.sm, vertical: 3),
        decoration: BoxDecoration(
          color: theme.colorScheme.surfaceContainerHighest,
          borderRadius: BorderRadius.circular(AppRadii.pill),
          border: Border.all(color: theme.colorScheme.outlineVariant),
        ),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(Icons.info_outline_rounded, size: 11, color: theme.colorScheme.onSurfaceVariant),
            const SizedBox(width: 4),
            Text(
              label,
              style: theme.textTheme.labelSmall?.copyWith(color: theme.colorScheme.onSurfaceVariant, letterSpacing: 0.2),
            ),
          ],
        ),
      ),
    );
  }
}
